version: '3.3'
services:
  db:
      image: postgres:15.1-alpine
      volumes:
        - db_data:/var/lib/postgresql/data/
        - ./codnity/scripts/db/:/docker-entrypoint-initdb.d
      env_file:
        - ./codnity/codnity/.env
      ports:
        - 5432:5432
  web:
    build: ./codnity
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./codnity:/usr/src/app/codnity
    ports:
      - "8000:8000"
    env_file:
      - ./codnity/codnity/.env
    depends_on:
      - db
volumes:
  db_data:
    driver: local