# Generated by Django 4.1.4 on 2022-12-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codnity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('points', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Codnity',
            },
        ),
    ]
